inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - !ruby/regexp /old_and_unused\.rb$/
    - lib/tasks/auto_annotate_models.rake

# The default 80 is too short
Metrics/LineLength:
  Max: 120

# This SHOULD be globally enabled instead
Style/FrozenStringLiteralComment:
  Enabled: false

# This really isn't a problem
Style/ClassAndModuleChildren:
  Enabled: false
