## This is the Travis CI config for the bot
## Please ensure you use the long-form name of flags e.g. --tag instead of -t
## This requires the following API tokens set in Travis CI:
## - HEROKU_API_KEY: available via `heroku auth:token`
## - HEROKU_STAGING_APP_NAME: the name of your production app to deploy
## - HEROKU_STAGING_APP_NAME: the name of your staging to deploy


language: generic

cache:
  directories:
    - docker-cache

env:
  - DATABASE_URL: postgres://localhost/test_db?pool=5

services:
  - docker
  - postgresql

# build the docker container
before_install:
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
  - docker pull registry.heroku.com/$HEROKU_STAGING_APP_NAME/web
  - docker pull registry.heroku.com/$HEROKU_STAGING_APP_NAME/release
  - docker build --tag worklark/worklark.web --tag registry.heroku.com/$HEROKU_STAGING_APP_NAME/web --file Dockerfile.web .
  - docker build --tag worklark/worklark.release --tag registry.heroku.com/$HEROKU_STAGING_APP_NAME/release --file Dockerfile.release .
  - curl https://cli-assets.heroku.com/install.sh | sh

# deploy the docker container
script:
  - docker run worklark/worklark.web "cd /app && RAILS_ENV=test bundle exec rake --trace db:create db:migrate test"
  - docker push registry.heroku.com/$HEROKU_STAGING_APP_NAME/web
  - docker push registry.heroku.com/$HEROKU_STAGING_APP_NAME/release
  - heroku container:release web release --app $HEROKU_STAGING_APP_NAME
notifications:
  slack: $SLACK_TRAVIS_APP_TOKEN
