FROM ruby:2.6.5

# Install dependencies, run initial setup, and output the version numbers used
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs ghostscript nodejs && \
    gem install bundler && \
    npm install -g yarn && \
    gem install bundler && \
    mkdir -p /app && mkdir -p /usr/local/nvm && \
    node -v && npm -v && yarn -v && bundle -v

WORKDIR /app

# Copy the Gemfile as well as the Gemfile.lock and install
# the RubyGems. This is a separate step so the dependencies
# will be cached unless changes to one of those two files
# are made.
COPY Gemfile Gemfile.lock package.json yarn.lock ./
RUN bundle install --verbose --jobs 20 --retry 5 && \
    yarn install --check-files

# Copy the main application.
COPY . ./

# precompile assets
RUN bundle exec rake assets:precompile

# Expose port 3000 to the Docker host, so we can access it
# from the outside.
EXPOSE 3000

# The main command to run when the container starts. Also
# tell the Rails dev server to bind to all interfaces by
# default.
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
